### ISSUE TITLE
how to use this starter kit for server-side rendering

### ISSUE THREAD

**Issue by thananan-l** [ManiruzzamanAkash/wp-react-kit#25]
I want to use this starter kit to develop server-side rendering plugin, what should I do?  Please guide me thanks

**Comment by ManiruzzamanAkash** [comment]
Hi @thananan-l, The demo block is rendered on Frontend by PHP - so the block is server side.

Which part do you exactly talking about ?
Are you talking about the Admin side to make that Server side instead of Client component ? But what is the philosophy of that ? If that is the case, you can just simply do that with PHP.

Our starter kit is pre-built for React, TypeScript, Tailwind CSS based. API's from PHP-WordPress.


Could you please clear more your context ?

**Comment by j7-dev** [comment]
Agree with @ManiruzzamanAkash 

If you want to SSR, just use PHP to do that.

It will be too complicated if you mix NEXT or other JS SSR framework with PHP.

**Comment by ManiruzzamanAkash** [comment]
Closing it, seems it's not clear or would not be suitable with our starter kit.
